language: go

go:
#  - 1.10.x
#  - 1.11.x
#  - 1.12.x
  - 1.13.x

#addons:
#  apt:
#    packages:
#      - rabbitmq-server

services:
  - mysql

env:
  - GO111MODULE=on db-host=127.0.0.1:3306 db-user=travis db-password= db-schema=mysql http-port=8080 grpc-port=9090 log-level=1 log-time-format=2006-01-02T15:04:05.999999999Z07:00

before_install:
  - chmod +x install-protobuf.sh
  - ./install-protobuf.sh
  - export GOPATH=$HOME/go
  - export GOBIN=$GOPATH/bin
  - export PATH=$PATH:$GOPATH:$GOBIN
  - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
  - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
  - go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger

script:
  - export GOPATH=$HOME/go
  - export GOBIN=$GOPATH/bin
  - export PATH=$PATH:$GOPATH:$GOBIN
  - sudo cp /home/travis/go/bin/protoc-gen-go /usr/local/bin/
  - sudo cp /home/travis/go/bin/protoc-gen-grpc-gateway /usr/local/bin/
  - sudo cp /home/travis/go/bin/protoc-gen-swagger /usr/local/bin/
  - sudo chmod +x /usr/local/bin/protoc-gen-go
  - sudo chmod +x /usr/local/bin/protoc-gen-grpc-gateway
  - sudo chmod +x /usr/local/bin/protoc-gen-swagger
  - sudo which protoc-gen-go
  - sudo ./third_party/protoc-gen.sh
  - go test -cpu=1,2 ./...