language: go

go:
#  - 1.10.x
#  - 1.11.x
#  - 1.12.x
  - 1.13.x

#addons:
#  apt:
#    packages:
#      - rabbitmq-server

services:
  - mysql

env:
  - GO111MODULE=on db-host=127.0.0.1:3306 db-user=travis db-password= db-schema=mysql http-port=8080 grpc-port=9090 log-level=1 log-time-format=2006-01-02T15:04:05.999999999Z07:00

before_install:
  - chmod +x install-protobuf.sh
#  - chmod +x /usr/local/bin/protoc
  - ./install-protobuf.sh
#  - export GOROOT=/home/travis/gopath
  - export GOPATH=$HOME/go
  - export GOBIN=$GOPATH/bin
  - export PATH=$PATH:$GOPATH:$GOBIN
#  - go get -v golang.org/x/lint/golint
#  - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
  - go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger

script:
#  - go env GOPATH
  - export GOPATH=$HOME/go
  - export GOBIN=$GOPATH/bin
  - export PATH=$PATH:$GOPATH:$GOBIN
#  - echo $PATH
#  - echo $GOBIN
#  - echo $GOPATH
#  - echo $GOROOT
#  - which protoc
  - which protoc-gen-go
#  - which protoc-gen-grpc-gateway
#  - which protoc-gen-swagger
#  - go mod download
  - sudo ./third_party/protoc-gen.sh
  - go test -cpu=1,2 ./...